package com.cobelliluetichperezvazquez.trabajointegrador.model.enums;

public enum CondicionIVA {
    IVA_RESPONSABLE_INSCRIPTO, IVA_SUJETO_EXTERNO, CONSUMIDOR_FINAL,
    RESPONSABLE_MONOTRIBUTO, SUJETO_NO_CATEGORIZADO, PROVEEDOR_DEL_EXTERIOR,
    CLIENTE_DEL_EXTERIOR, IVA_LIBERADO, PEQUEÑO_CONTRIBUYENTE_EVENTUAL,
    PEQUEÑO_CONTRIBUYENTE_EVENTUAL_SOCIAL, MONOTRIBUTISTA_SOCIAL
}
